In [58]:
import seaborn as sns
import numpy as np

In [59]:
# 데이터 불러오기
iris = sns.load_dataset('iris')
X = iris.drop('species', axis=1)
y = iris['species']
print(np.unique(y))

['setosa' 'versicolor' 'virginica']


## axis=1을 사용하는 것은 열을 대상으로 작업하고 싶을 때
## axis=0은 행을 대상으로 작업하고 싶을 때 사용

In [60]:
# 데이터 전처리
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y.values)
print(np.unique(y))

[0 1 2]


In [61]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1,stratify=y)

In [62]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(C=1e2, random_state=1, max_iter=200)
# default: L2 regularization
classifier.fit(X_train, y_train)
y_train_pred = classifier.predict(X_train)
y_test_pred = classifier.predict(X_test)
y_test_pred_proba = classifier.predict_proba(X_test)
print(y_test_pred_proba[:5])

[[6.03658915e-10 5.77393372e-04 9.99422606e-01]
 [9.98993210e-01 1.00678999e-03 1.80975600e-20]
 [9.99808999e-01 1.91001022e-04 3.07456426e-21]
 [3.19391069e-05 4.41167321e-01 5.58800740e-01]
 [2.07899507e-05 9.99319018e-01 6.60192314e-04]]


In [63]:
from sklearn.metrics import accuracy_score, confusion_matrix

print(accuracy_score(y_train, y_train_pred))
print(accuracy_score(y_test, y_test_pred))
print(confusion_matrix(y_test, y_test_pred))

0.9809523809523809
1.0
[[15  0  0]
 [ 0 15  0]
 [ 0  0 15]]


In [64]:
# 학습된 모형을 저장한 후 불러와서 사용하기

import joblib

joblib.dump(classifier, '/Users/junwlee/Documents/KoreaUniv/24-Spring/Statistics&ML/practice/LogisticRegression/save.pkl')
classifier_from_joblib = joblib.load('/Users/junwlee/Documents/KoreaUniv/24-Spring/Statistics&ML/practice/LogisticRegression/save.pkl')

classifier_pred = classifier_from_joblib.predict(X_test)
print(accuracy_score(y_test, classifier_pred))

1.0
